//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _BookNeT_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookFeedbackG
    {
        public int FeedbackID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FeedbackText { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
        public Nullable<int> BookID { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
    }
}
