//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _BookNeT_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.BookFeedback = new HashSet<BookFeedback>();
            this.Borrowing = new HashSet<Borrowing>();
            this.Purchases = new HashSet<Purchases>();
            this.ShoppingCart = new HashSet<ShoppingCart>();
            this.WaitingList = new HashSet<WaitingList>();
            this.UserBookHistory = new HashSet<UserBookHistory>();
            this.UserFavoriteBooks = new HashSet<UserFavoriteBooks>();
        }
    
        public int BookID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public Nullable<int> YearOfPublication { get; set; }
        public string Formats { get; set; }
        public string Genre { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> BorrowPrice { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<bool> IsBorrowable { get; set; }
        public Nullable<int> AgeRestriction { get; set; }
        public Nullable<bool> IsDiscounted { get; set; }
        public Nullable<System.DateTime> DiscountEndDate { get; set; }
        public Nullable<System.DateTime> BorrowDate { get; set; }
        public string Status { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> DiscountPercentage { get; set; }
        public string Description { get; set; }

        public decimal CalculateDiscountedPrice()
        {
            // ????? ??? ???? ?????
            if (IsDiscounted.HasValue && IsDiscounted.Value && DiscountPercentage.HasValue && PurchasePrice.HasValue)
            {
                // ????? ????? ???? ????
                return PurchasePrice.Value - (PurchasePrice.Value * (DiscountPercentage.Value / 100m));
            }

            // ?? ??? ????, ????? ?? ????? ?????
            return PurchasePrice ?? 0m; // ????? 0 ?? PurchasePrice ??? null
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookFeedback> BookFeedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borrowing> Borrowing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchases> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaitingList> WaitingList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBookHistory> UserBookHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFavoriteBooks> UserFavoriteBooks { get; set; }
    }
}
