//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _BookNeT_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BooknetProjectEntities2 : DbContext
    {
        public BooknetProjectEntities2()
            : base("name=BooknetProjectEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookFeedback> BookFeedback { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Borrowing> Borrowing { get; set; }
        public virtual DbSet<Purchases> Purchases { get; set; }
        public virtual DbSet<ServiceFeedback> ServiceFeedback { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCart { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WaitingList> WaitingList { get; set; }
        public virtual DbSet<UserBookHistory> UserBookHistory { get; set; }
        public virtual DbSet<UserFavoriteBooks> UserFavoriteBooks { get; set; }
    }
}
